BEGIN TRANSACTION;
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test1","Test1_FAM","Test1_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test2","Test2_FAM","Test2_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test3","Test3_FAM","Test3_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test4","Test4_FAM","Test4_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test5","Test5_FAM","Test5_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test6","Test6_FAM","Test6_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test7","Test7_FAM","Test7_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test8","Test8_FAM","Test8_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test9","Test9_FAM","Test9_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test10","Test10_FAM","Test10_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test11","Test11_FAM","Test11_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test12","Test12_FAM","Test12_Name");
INSERT INTO contacts(version,fn,family_name, given_name)VALUES("3.0","Test13","Test13_FAM","Test13_Name");
COMMIT;